-- !Ups

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL,
  PASSWORD_HASH VARCHAR(60) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROOMS (
  ID VARCHAR(5) NOT NULL,
  GAME_ID VARCHAR(40) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PLAYERS (
  USER_ID INT NOT NULL,
  ROOM_ID VARCHAR(5) NOT NULL,
  POSITION INT NOT NULL,
  IS_OWNER BOOLEAN NOT NULL,
  PRIMARY KEY (ROOM_ID, POSITION),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)
);

CREATE TABLE ACTIONS (
  ROOM_ID VARCHAR(5) NOT NULL,
  POSITION INT NOT NULL,
  USER_ID INT NOT NULL,
  ACTION_HASH VARCHAR(60) NOT NULL,
  TIMESTAMP LONG NOT NULL,
  PRIMARY KEY (ROOM_ID, POSITION),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- !Downs

DROP TABLE ACTIONS;
DROP TABLE PLAYERS;
DROP TABLE ROOMS;
DROP TABLE USERS;